### PR TITLE
Fixing #348 - Fixing missing KEY options for MySQL and MariaDB

### LINKED ISSUE #348: Missing KEY options
Ref: https://dev.mysql.com/doc/refman/8.0/en/create-table.html
Ref: https://mariadb.com/kb/en/create-table/

### PR DESCRIPTION
**Pull request by iifawzi**
Hi, this PR continued the work at https://github.com/phpmyadmin/sql-parser/pull/349 and should fix #348 and https://github.com/phpmyadmin/phpmyadmin/issues/17097. 
I've also added a test for the invisible key issue.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you for this one too ! 💯 😍

File: tests/Parser/CreateStatementTest.php [hunk 1]
```diff
@@ -47,6 +47,7 @@ public function createProvider()
             array('parser/parseCreateTableLike'),
             array('parser/parseCreateTableSpatial'),
             array('parser/parseCreateTableTimestampWithPrecision'),
+            array('parser/parseCreateTableWithInvisibleKey'),
```
Comment (williamdes) [inline tests/Parser/CreateStatementTest.php:50]: I added this one ;)

Comment (iifawzi) [reply tests/Parser/CreateStatementTest.php:50]: Thank you and sorry, missed.
