### PR TITLE
Fixing #341 - Fixing validation exception when using enforced option

### LINKED ISSUE #341: Perfectly valid CHECK constraint on MySQL query throws a validation exception
### Describe the bug

When I write a simple MySQL query, with a `CHECK` constraint, and add the `ENFORCED` keyword, the validation of the query fails.

### To Reproduce

1. Run MySQL container with Docker `docker run --name mysql --rm -dit --env MYSQL_ROOT_PASSWORD=test123 mysql:8.0.26`
1. Run phpMyAdmin container with Docker `docker run --detach --env PMA_ARBITRARY=1 --publish 37298:80 phpmyadmin`
1. Find MySQL server container private IP address `docker inspect mysql`
1. Login to web interface `http://localhost:37298`
1. Go to SQL tab
1. Insert query below
1. Observe the red line under `ENFORCED`
1. Hover mouse over error icon on affected line
1. Observe the error message `A comma or a closing bracket was expected. (near ENFORCED)`

```sql
CREATE DATABASE IF NOT EXISTS cbt_triggers;
USE cbt_triggers;
DROP TABLE IF EXISTS employees_check;
CREATE TABLE IF NOT EXISTS employees_check (FirstName varchar(30) CHECK (FirstName REGEXP '^T' AND FirstName REGEXP 'r$') ENFORCED);
```

### Expected behavior

No query validation exceptions should be shown, nor any red lines indicating a validation exception.

### Screenshots

image

image

### Server configuration

- Operating system: Docker Desktop for Windows 10, with WSL2 integration
- Web server: Apache
- Database version: MySQL 8.0.26
- PHP version: 7.4.22
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Firefox 91
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by iifawzi**
Hi, this PR should fix #341

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you so much ! 💯 😍

File: src/Components/CreateDefinition.php [hunk 1]
```diff
@@ -85,8 +85,8 @@ class CreateDefinition extends Component
             'expr',
             array('parenthesesDelimited' => true),
         ),
-
         'INVISIBLE' => 13,
+        'ENFORCED' => 14,
```
Comment (williamdes) [inline src/Components/CreateDefinition.php:89]: Would `NOT ENFORCED` still work ?
https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html

**Review by williamdes — APPROVED** [review]
💯
