### PR TITLE
Fix #430 - `ALTER TABLE … RENAME COLUMN … TO …` is not understood by the parser/linter 

### LINKED ISSUE #430: `ALTER TABLE … RENAME COLUMN … TO …` not understood by the parser/linter
When trying to parse the following SQL statement, the `AlterStatement` createed regarding this SQL is missing the "TO" option and the new name of the column.

```sql
ALTER TABLE potato RENAME COLUMN `KIND` TO `VARIETY`;
```

The linter give also the error:
```
> bin/lint-query --query 'ALTER TABLE potato RENAME COLUMN `KIND` TO `VARIETY`;'
#1: Virgule manquante avant le début d’une nouvelle opération ALTER. (near "TO" at position 40)
```
(French translation for `"#1: Missing comma before the beginning of a new ALTER operation."`).

### PR DESCRIPTION
**Pull request by niconoe-**
Fixes #430 

I agree that this PR adds a specific management case for the RENAME COLUMN. If you find this too specific, you could try to give me hints on how to do this in a cleaner way, as I'm unsure this could be possible.

Thanks.

### CODE REVIEW

**Comment by niconoe-** [comment]
Failing checks are only due to unmodified files. I don't expect to fix them on this PR.

**Review by williamdes — APPROVED** [review]
Looks good !
Out of curiosity, what happens to a query that renames two columns and also renames an index ?
Is it possible ?
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

**Comment by niconoe-** [comment]
Unit tests added via a provider to easily add some more.

And after some tests, it appears that there was just an extra space in the builder but after a trim, everything works fine ;)

File: src/Components/AlterOperation.php [hunk 1]
```diff
@@ -485,18 +493,27 @@ public static function parse(Parser $parser, TokensList $list, array $options =
...
 
-        $ret .= TokensList::build($component->unknown);
+        $ret .= $afterFieldsOptions . TokensList::build($component->unknown);
 
         if (isset($component->partitions)) {
             $ret .= PartitionDefinition::build($component->partitions);
         }
 
-        return $ret;
+        return trim($ret);
```
Comment (williamdes) [inline src/Components/AlterOperation.php:516]: maybe add a second param to specify what we want to trim ?

Comment (niconoe-) [reply src/Components/AlterOperation.php:516]: I expect to trim any whitespace character (defaut value) as it looks like the default behavior to me (removing whitespaces **before** comma).

Comment (williamdes) [reply src/Components/AlterOperation.php:516]: But it will also trim new lines ;)
That's okay, I had a look and the parser mostly uses trim without any other param

Comment (niconoe-) [reply src/Components/AlterOperation.php:516]: > But it will also trim new lines ;) 

I know and I'm ok with this. When the builder is asked to build a statement, I don't expect something like this:
```sql
ALTER TABLE myTable RENAME COLUMN foo TO bar
, ADD foo VARCHAR(255) NOT NULL;
```
but rather something like:
```sql
ALTER TABLE myTable RENAME COLUMN foo TO bar, ADD foo VARCHAR(255) NOT NULL;
```

Thats' a style point of view but having whitespaces (including new lines) **before** a comma is usually not expected.

> That's okay, I had a look and the parser mostly uses trim without any other param

Thanks :wink:

**Comment by niconoe-** [comment]
I wasn't able to hard set onto 5.8.x so I create a new PR (#433) from a branch that starts from 5.8.x and cherry-picks my (fixed-up) commits.

**Comment by williamdes** [comment]
> I wasn't able to hard set onto 5.8.x so I create a new PR (#433) from a branch that starts from 5.8.x and cherry-picks my (fixed-up) commits.
> 
> You can close this PR now, if #433 is OK for you.

Well, let's keep this one ;)
What I did is reset hard to your other branch, and force push this one to it

**Review by williamdes — APPROVED** [review]
All green ✅
